# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chubr/noVax

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chubr/noVax

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chubr/noVax/CMakeFiles /home/chubr/noVax//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chubr/noVax/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named q

# Build rule for target.
q : cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 q
.PHONY : q

# fast build rule for target.
q/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/build
.PHONY : q/fast

panel_mem.o: panel_mem.cpp.o
.PHONY : panel_mem.o

# target to build an object file
panel_mem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_mem.cpp.o
.PHONY : panel_mem.cpp.o

panel_mem.i: panel_mem.cpp.i
.PHONY : panel_mem.i

# target to preprocess a source file
panel_mem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_mem.cpp.i
.PHONY : panel_mem.cpp.i

panel_mem.s: panel_mem.cpp.s
.PHONY : panel_mem.s

# target to generate assembly for a file
panel_mem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_mem.cpp.s
.PHONY : panel_mem.cpp.s

panel_msg.o: panel_msg.cpp.o
.PHONY : panel_msg.o

# target to build an object file
panel_msg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_msg.cpp.o
.PHONY : panel_msg.cpp.o

panel_msg.i: panel_msg.cpp.i
.PHONY : panel_msg.i

# target to preprocess a source file
panel_msg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_msg.cpp.i
.PHONY : panel_msg.cpp.i

panel_msg.s: panel_msg.cpp.s
.PHONY : panel_msg.s

# target to generate assembly for a file
panel_msg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_msg.cpp.s
.PHONY : panel_msg.cpp.s

panel_regs.o: panel_regs.cpp.o
.PHONY : panel_regs.o

# target to build an object file
panel_regs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_regs.cpp.o
.PHONY : panel_regs.cpp.o

panel_regs.i: panel_regs.cpp.i
.PHONY : panel_regs.i

# target to preprocess a source file
panel_regs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_regs.cpp.i
.PHONY : panel_regs.cpp.i

panel_regs.s: panel_regs.cpp.s
.PHONY : panel_regs.s

# target to generate assembly for a file
panel_regs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_regs.cpp.s
.PHONY : panel_regs.cpp.s

panel_srch.o: panel_srch.cpp.o
.PHONY : panel_srch.o

# target to build an object file
panel_srch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_srch.cpp.o
.PHONY : panel_srch.cpp.o

panel_srch.i: panel_srch.cpp.i
.PHONY : panel_srch.i

# target to preprocess a source file
panel_srch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_srch.cpp.i
.PHONY : panel_srch.cpp.i

panel_srch.s: panel_srch.cpp.s
.PHONY : panel_srch.s

# target to generate assembly for a file
panel_srch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/panel_srch.cpp.s
.PHONY : panel_srch.cpp.s

start.o: start.cpp.o
.PHONY : start.o

# target to build an object file
start.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/start.cpp.o
.PHONY : start.cpp.o

start.i: start.cpp.i
.PHONY : start.i

# target to preprocess a source file
start.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/start.cpp.i
.PHONY : start.cpp.i

start.s: start.cpp.s
.PHONY : start.s

# target to generate assembly for a file
start.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/q.dir/build.make CMakeFiles/q.dir/start.cpp.s
.PHONY : start.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... q"
	@echo "... panel_mem.o"
	@echo "... panel_mem.i"
	@echo "... panel_mem.s"
	@echo "... panel_msg.o"
	@echo "... panel_msg.i"
	@echo "... panel_msg.s"
	@echo "... panel_regs.o"
	@echo "... panel_regs.i"
	@echo "... panel_regs.s"
	@echo "... panel_srch.o"
	@echo "... panel_srch.i"
	@echo "... panel_srch.s"
	@echo "... start.o"
	@echo "... start.i"
	@echo "... start.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

