name: CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  schedule:
  - cron: "00 12 1 * *"

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache wxwidgets
      uses: actions/cache@v2
      with:
        path: |
         wxWidgets-install
         googleTest-install
        key: ${{ runner.os }}-wxwidgets-${{ hashFiles('**/yml_file') }}

    - name: Install google test
      run: |
        if [ -d googleTest-install ]; then 
          echo "googleTest-install cache hit" 
        else
          sudo apt update &&
          git clone https://github.com/google/googletest.git  --depth 1 &&
          cd googletest/ &&
          mkdir build &&
          cd build &&
          cmake -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/googleTest-install ..  &&
          make  -j 2 &&
          make install 
        fi
        
    - name: Install wxwidgets
      run: |
        if [ -d wxWidgets-install ]; then 
          echo "wxWidgets cache hit" 
        else
          sudo apt update &&
          sudo apt install -y libgtk-3-dev &&
          git clone https://github.com/wxWidgets/wxWidgets.git --depth 1 &&
          cd wxWidgets/ &&
          mkdir build-gtk &&
          cd build-gtk &&
          git submodule update --init --recursive &&
          ../configure --prefix=${{github.workspace}}/wxWidgets-install &&
          make -j 2 &&
          make install 
        fi


    - name: Configure CMake GUI
      env:
        googletest_ROOT_DIR: ${{github.workspace}}/googleTest-install
        wxWidgets_ROOT_DIR: ${{github.workspace}}/wxWidgets-install
      run: cd noVaxGUI && cmake -B ${{github.workspace}}/noVaxGUI/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DwxWidgets_ROOT_DIR=${{github.workspace}}/wxWidgets-install -Dgoogletest_ROOT_DIR=${{github.workspace}}/googleTest-install

    - name: Build GUI
      run: cd noVaxGUI && cmake --build ${{github.workspace}}/noVaxGUI/build --config ${{env.BUILD_TYPE}}

    - name: Configure CMake CLI
      env:
        googletest_ROOT_DIR: ${{github.workspace}}/googleTest-install
      run: cd noVaxCLIDevTools && cmake -B ${{github.workspace}}/noVaxCLIDevTools/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dgoogletest_ROOT_DIR=${{github.workspace}}/googleTest-install


    - name: Build CLI
      env:
        googletest_ROOT_DIR: ${{github.workspace}}/googleTest-install
      run: cd noVaxCLIDevTools && cmake --build ${{github.workspace}}/noVaxCLIDevTools/build --config ${{env.BUILD_TYPE}}

    - name: Run Tests
      env:
        CPROCESSOR_TEST_PATH: ${{github.workspace}}/noVaxEngine/tests/file/Cprocessor_save_load/
      run: cd ${{github.workspace}}/noVaxEngine_binary && ./runTests
